-- A zero target bid is not a small bid.
--
-- The parameter contract admitted '0' because its pattern allowed it and its
-- pattern was the only test the target had to pass. On every marketplace this
-- product would talk to, a bid of zero either withdraws the object from auction
-- or is refused outright. Withdrawing an object is a status change, which this
-- product does not write, so a zero that reached a command would be a
-- capability nobody granted arriving through a validation gap.
--
-- The Java contract already refused it. This makes the two agree, and a parity
-- test asserts that they still do.
--
-- Forward-only: the function is replaced, no data is touched, and the set of
-- accepted parameter shapes only narrows.

CREATE OR REPLACE FUNCTION ops.ad_bid_parameter_contract_is_valid(p_parameters jsonb)
RETURNS boolean
LANGUAGE sql IMMUTABLE
SET search_path = pg_catalog, pg_temp
AS $$
    SELECT p_parameters IS NOT NULL
       AND jsonb_typeof(p_parameters) = 'object'
       AND (p_parameters - 'candidateId' - 'direction' - 'targetBid') = '{}'::jsonb
       AND p_parameters ? 'candidateId'
       AND p_parameters ? 'direction'
       AND p_parameters ? 'targetBid'
       AND (p_parameters ->> 'candidateId') ~
           '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
       AND (p_parameters ->> 'direction') IN
           ('PROTECTION_DECREASE', 'OPTIMIZATION_INCREASE', 'EXACT_PRIOR_BID_COMPENSATION')
       AND (p_parameters ->> 'targetBid') ~ '^[0-9]{1,14}([.][0-9]{1,4})?$'
       AND (p_parameters ->> 'targetBid')::numeric > 0
$$;
REVOKE ALL ON FUNCTION ops.ad_bid_parameter_contract_is_valid(jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION ops.ad_bid_parameter_contract_is_valid(jsonb) TO marketops_app;

-- A candidate that proposes zero cannot become a command either. The check is
-- added here rather than left to the parameter contract because a candidate is
-- generated by this product, and generating one nobody may act on is a defect
-- worth refusing at the point it happens.
ALTER TABLE ops.ad_bid_candidate
    ADD CONSTRAINT ad_bid_candidate_target_positive_ck
    CHECK (provider_normalized_amount > 0);
