from pathlib import Path
import collections,hashlib,json,subprocess
ROOT=Path('/Users/chzhengx/Code/personal/marketops-platform');OUT=Path(__file__).resolve().parent;PRIOR=Path('/tmp/slice3-checkpoint-ci-7e66cf8');HEAD='1381ef78594875a1e1304e4d9a636e49d0fab71f';MERGE='ddec24ca37d71a61772b6682e633d7536da1cb3e';OLDHEAD='7e66cf87afc15773d4f6e6e6717a86e7b8336ae5'
sha=lambda b:hashlib.sha256(b).hexdigest();load=lambda p:json.loads(p.read_bytes());old=load(PRIOR/'ALERT-DELTA-TRIAGE.json');prior={x['number']:x for x in old['findings']};current=[x for page in load(OUT/'open-alerts-pages-r1.json') for x in page];cache={}
def content(head,path):
 k=(head,path)
 if k not in cache:cache[k]=subprocess.check_output(['git','show',head+':'+path],cwd=ROOT)
 return cache[k]
def expression(b,loc):
 lines=b.decode().splitlines(keepends=True)[loc['start_line']-1:loc['end_line']]
 if len(lines)==1:return lines[0][loc['start_column']-1:loc['end_column']-1]
 lines[0]=lines[0][loc['start_column']-1:];lines[-1]=lines[-1][:loc['end_column']-1];return ''.join(lines)
rows=[]
for a in sorted(current,key=lambda x:x['number']):
 loc=a['most_recent_instance']['location'];raw=content(HEAD,loc['path']);ex=expression(raw,loc);row={'number':a['number'],'ruleId':a['rule']['id'],'level':a['rule']['severity'],'securitySeverity':a['rule'].get('security_severity_level'),'state':a['state'],'currentLocation':loc,'currentCommit':a['most_recent_instance']['commit_sha'],'currentSourceSha256':sha(raw),'currentFlaggedExpressionSha256':sha(ex.encode())};assert row['currentCommit']==MERGE
 if a['number'] in prior:
  prev=prior[a['number']];prevraw=content(OLDHEAD,prev['currentLocation']['path']);prevex=expression(prevraw,prev['currentLocation']);same=ex==prevex;assert sha(prevex.encode())==prev['currentFlaggedExpressionSha256'];row.update(priorSourceHead=OLDHEAD,previousLocation=prev['currentLocation'],sameExactFlaggedExpression=same,sameWholeFile=raw==prevraw,locationMoved=loc!=prev['currentLocation'],previousDisposition=prev['disposition'],priorEngineeringAssessment=prev['engineeringAssessment'],priorTriage=prev.get('priorTriage'),engineeringAssessment='Exact flagged expression is unchanged against the previous checkpoint; prior bounded disposition is preserved and current source/location are independently bound.' if same else 'CHANGED_EXPRESSION_REQUIRES_SPECIFIC_REVIEW',disposition='HISTORICAL_OPEN_QUALITY_NOTE_OR_WARNING_RECHECKED' if same else 'REVIEW_REQUIRED')
 else:row.update(disposition='NEW_ALERT_REQUIRES_SPECIFIC_REVIEW',engineeringAssessment='No historical disposition is adopted for a newly observed alert.')
 rows.append(row)
result={'kind':'EXACT_CHECKPOINT_OPEN_ALERT_DELTA_AND_BOUNDED_TRIAGE','sourceHead':HEAD,'testedMerge':MERGE,'priorSourceHead':OLDHEAD,'priorEvidence':{'path':str(PRIOR/'ALERT-DELTA-TRIAGE.json'),'sha256':sha((PRIOR/'ALERT-DELTA-TRIAGE.json').read_bytes())},'priorOpenCount':len(prior),'priorW8OpenCount':87,'currentOpenCount':len(current),'added':sorted({x['number'] for x in current}-prior.keys()),'removed':sorted(prior.keys()-{x['number'] for x in current}),'levelCounts':dict(collections.Counter(x['level'] for x in rows)),'newSecuritySeverityFindings':sum(x['securitySeverity'] is not None for x in rows if x['number'] not in prior),'historicalExactExpressionMatches':sum(x.get('sameExactFlaggedExpression') is True for x in rows),'historicalWholeFileMatches':sum(x.get('sameWholeFile') is True for x in rows),'historicalChangedExpressions':[x['number'] for x in rows if x.get('sameExactFlaggedExpression') is False],'wholeFileChangedWithSameExpression':[x['number'] for x in rows if x.get('sameWholeFile') is False and x.get('sameExactFlaggedExpression') is True],'findings':rows,'controllerApprovalClaimMade':False,'alertDismissalsPerformed':False,'boundary':'Open quality notes/warnings remain open; no zero-quality-finding or zero-raw-security-HIGH claim. Newly observed and changed expressions require actual specific review.'}
(OUT/'ALERT-DELTA-TRIAGE.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({k:result[k] for k in ['priorOpenCount','currentOpenCount','added','removed','historicalExactExpressionMatches','historicalWholeFileMatches','historicalChangedExpressions','wholeFileChangedWithSameExpression']}))
