#!/usr/bin/env python3
"""Review current exact nonsecurity log/artifact scopes without synthesizing named tests."""
import argparse,datetime,hashlib,json,pathlib,re,sys,time
from capture_ci import checked_zip,ref,need,save
ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('--capture-dir',type=pathlib.Path,required=True);ap.add_argument('--frontend-files',type=int,required=True);ap.add_argument('--frontend-tests',type=int,required=True);ap.add_argument('--governance-tests',type=int,required=True);a=ap.parse_args();P=a.capture_dir.resolve()
need(all(x>0 for x in (a.frontend_files,a.frontend_tests,a.governance_tests)),'Supply actual measured current-source totals; no historical defaults')
decoderStartedAt=datetime.datetime.now(datetime.timezone.utc).isoformat();decoderClock=time.monotonic()
capture=json.loads((P/'CI-CAPTURE-RECEIPT.json').read_bytes());need(capture['result']=='CAPTURE_COMPLETE_REQUIRES_BACKEND_AND_SECURITY_REVIEW' and capture['exitCode']==0,'A complete successful exact capture is required')
need(ref(capture['logIndex']['path'])==capture['logIndex'],'Log index changed');need(ref(capture['artifactIndex']['path'])==capture['artifactIndex'],'Artifact index changed')
logs=json.loads(pathlib.Path(capture['logIndex']['path']).read_bytes())['archives'];artifacts=json.loads(pathlib.Path(capture['artifactIndex']['path']).read_bytes())['artifacts'];rawlines={};logbind={};ansi=re.compile(r'\x1b\[[0-9;]*m')
for log in logs:
 if log['workflow'] not in {'Frontend','Governance','Infrastructure'}:continue
 need(ref(log['archive']['path'])==log['archive'],'Original log archive changed')
 with checked_zip(pathlib.Path(log['archive']['path'])) as z:
  for member in log['members']:
   n=member['member'];b=z.read(n);need(hashlib.sha256(b).hexdigest()==member['sha256'],'Log member mismatch');need(n not in rawlines,'Log namespace ambiguous');rawlines[n]=[ansi.sub('',x) for x in b.decode('utf-8','replace').splitlines()];logbind[n]={'archive':log['archive'],'member':n,'memberSha256':member['sha256'],'workflow':log['workflow'],'runId':log['runId'],'attempt':log['attempt']}
def proof(name,pattern):
 need(name in rawlines,'Exact source-defined workflow step missing: '+name);got=[{'line':n+1,'text':s} for n,s in enumerate(rawlines[name]) if re.search(pattern,s)];need(got,'Expected actual log evidence absent: '+name+' '+pattern);return dict(logbind[name],lines=got)
frontend={'unitSourceFiles':a.frontend_files,'unitTests':a.frontend_tests,'unitEvidence':[proof('frontend-test/6_Run the tests with coverage.txt',rf'\bTest Files\s+{a.frontend_files} passed\b'),proof('frontend-test/6_Run the tests with coverage.txt',rf'\bTests\s+{a.frontend_tests} passed\b')],'coverageNegative':proof('frontend-test/7_Prove the frontend coverage gate rejects an unmet threshold.txt',r'coverage-negative: frontend threshold enforcement PASS'),'bundleIsolation':proof('frontend-build/5_Prove that only prefixed values reached the bundle.txt',r'bundle isolation PASS'),'browserLegacyTests':25,'browserGovernedTests':12,'browserTotalTests':37,'browserEvidence':[proof('frontend-test/11_Exercise authenticated business flow and dependency recovery in Chromium.txt',r'25 passed'),proof('frontend-test/13_Exercise governed advertising roles in a fresh isolated database.txt',r'12 passed')],'scope':'Distinct actual steps only. The source-equivalent workflow does not upload browser named JUnit; these log totals do not create named nodes.'}
governance={'validatorTests':a.governance_tests,'evidence':[proof("governance/6_Run the validator's own tests.txt",rf'\bRan {a.governance_tests} tests\b'),proof("governance/6_Run the validator's own tests.txt",r'\bOK$')],'scope':'Actual remote governance validator suite only. Any local additional tool suites retain their own actual run/source identities; remote governance logs are not tool rerun evidence.'}
infra={'networkAndSecretRefusalTests':9,'ephemeralSecretDeliveryTests':13,'evidence':[proof('infrastructure-validation/5_Test network and secret-delivery refusal controls.txt',r'Ran 9 tests'),proof('infrastructure-validation/5_Test network and secret-delivery refusal controls.txt',r'\bOK$'),proof('infrastructure-validation/6_Test ephemeral runtime secret delivery.txt',r'Ran 13 tests'),proof('infrastructure-validation/6_Test ephemeral runtime secret delivery.txt',r'\bOK$')]}
for x in artifacts:
 if x['officialMetadata']['name']!='infrastructure-verification':continue
 need(ref(x['archive']['path'])==x['archive'],'Infrastructure archive changed')
 with checked_zip(pathlib.Path(x['archive']['path'])) as z:
  b=z.read('summary.json');member=next(m for m in x['members'] if m['member']=='summary.json');need(hashlib.sha256(b).hexdigest()==member['sha256'],'Infrastructure member changed');summary=json.loads(b);need(summary['real_provider_api_calls']=='NONE_MOCK_PROVIDER' and all(p['apply']=='NOT_EXECUTED' and p['external_verification']=='NOT_PERFORMED' for p in summary['plans']),'Infrastructure boundary differs');infra['actualMockPlanSummary']=summary;infra['summaryEvidence']={'archive':x['archive'],'member':member,'runId':x['runId'],'attempt':x['attempt'],'jobId':x['jobId']}
need('actualMockPlanSummary' in infra,'Missing infrastructure summary')
receipt={'kind':'EXACT_FINAL_CONTAINING_NONSECURITY_COMPLETED_SCOPE_REVIEW','sourceHead':capture['sourceHead'],'sourceTree':capture['sourceTree'],'testedMerge':capture['testedMerge'],'testedMergeParents':capture['testedMergeParents'],'captureReceipt':ref(P/'CI-CAPTURE-RECEIPT.json'),'sourceBinding':capture['sourceBinding'],'toolInputs':{'decoder':ref(__file__),'captureHelper':ref(pathlib.Path(__file__).with_name('capture_ci.py'))},'completedScopeSummaries':{'frontend':frontend,'governance':governance,'infrastructure':infra},'requiredContexts':capture['contexts'],'backendScope':'Original XML/capacity/coverage reviewed by separate decode_backend.py receipt.','securityScope':'Only original exact run/attempt/job/check metadata is collected here; separate Security evidence remains required.','rawPublicationSafetyReview':'NOT_PERFORMED','localProductExecutionPerformed':False,'productionWriteEnabled':False,'proofsCreated':0,'engineeringClosureClaimMade':False,'controllerApprovalClaimMade':False,'expectedCurrentSourceCounts':{'frontendFiles':a.frontend_files,'frontendTests':a.frontend_tests,'governanceTests':a.governance_tests},'argv':[sys.executable,*sys.argv],'startedAt':decoderStartedAt,'finishedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'elapsedSeconds':round(time.monotonic()-decoderClock,3),'exitCode':0}
print(json.dumps(save(P/'NONSECURITY-CI-CONTAINING-RECEIPT.json',receipt)))
