package com.mimococo.marketops.marketplaceintegration.internal.infrastructure.jdbc;

import com.mimococo.marketops.marketplaceintegration.internal.domain.FeatureFlag;
import com.mimococo.marketops.marketplaceintegration.internal.domain.FlagKind;
import com.mimococo.marketops.marketplaceintegration.internal.domain.FlagScopeKind;
import com.mimococo.marketops.marketplaceintegration.internal.domain.FlagState;
import com.mimococo.marketops.marketplaceintegration.internal.domain.RegistryStatus;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

/**
 * Relational access to {@code platform.feature_flag}.
 *
 * <p>The stored {@code scope_key} column is generated by the database from the
 * scope kind and reference columns; the application never writes it.
 */
@Repository
public class FeatureFlagRepository {

    private final JdbcClient jdbc;

    FeatureFlagRepository(JdbcClient jdbc) {
        this.jdbc = jdbc;
    }

    /** Insert a new flag row. */
    public void insert(FeatureFlag flag) {
        jdbc.sql("""
                        INSERT INTO platform.feature_flag (
                            id, flag_code, flag_kind, scope_kind, platform_code,
                            marketplace_account_id, store_id, capability_id, state,
                            description, reason, status, created_at, updated_at, version)
                        VALUES (:id, :flagCode, :flagKind, :scopeKind, :platformCode,
                            :marketplaceAccountId, :storeId, :capabilityId, :state,
                            :description, :reason, :status, :createdAt, :updatedAt, :version)
                        """)
                .param("id", flag.id())
                .param("flagCode", flag.flagCode())
                .param("flagKind", flag.flagKind().name())
                .param("scopeKind", flag.scopeKind().name())
                .param("platformCode", flag.platformCode())
                .param("marketplaceAccountId", flag.marketplaceAccountId())
                .param("storeId", flag.storeId())
                .param("capabilityId", flag.capabilityId())
                .param("state", flag.state().name())
                .param("description", flag.description())
                .param("reason", flag.reason())
                .param("status", flag.status().name())
                .param("createdAt", Timestamp.from(flag.createdAt()))
                .param("updatedAt", Timestamp.from(flag.updatedAt()))
                .param("version", flag.version())
                .update();
    }

    /** Apply a versioned update; false means the expected version was stale. */
    public boolean update(FeatureFlag flag, long expectedVersion) {
        int updated = jdbc.sql("""
                        UPDATE platform.feature_flag
                        SET state = :state, description = :description, reason = :reason,
                            status = :status, updated_at = :updatedAt, version = :newVersion
                        WHERE id = :id AND version = :expectedVersion
                        """)
                .param("state", flag.state().name())
                .param("description", flag.description())
                .param("reason", flag.reason())
                .param("status", flag.status().name())
                .param("updatedAt", Timestamp.from(flag.updatedAt()))
                .param("newVersion", expectedVersion + 1)
                .param("id", flag.id())
                .param("expectedVersion", expectedVersion)
                .update();
        return updated == 1;
    }

    /** Load one flag. */
    public Optional<FeatureFlag> findById(UUID id) {
        return jdbc.sql("SELECT * FROM platform.feature_flag WHERE id = :id")
                .param("id", id)
                .query(FeatureFlagRepository::map)
                .optional();
    }

    /** Load the active flag with this code and exact scope, if any. */
    public Optional<FeatureFlag> findActiveByScope(
            String flagCode, FlagScopeKind scopeKind, String platformCode,
            UUID marketplaceAccountId, UUID storeId, UUID capabilityId) {
        return jdbc.sql("""
                        SELECT * FROM platform.feature_flag
                        WHERE flag_code = :flagCode AND scope_kind = :scopeKind
                          AND platform_code IS NOT DISTINCT FROM CAST(:platformCode AS text)
                          AND marketplace_account_id IS NOT DISTINCT FROM
                              CAST(:marketplaceAccountId AS uuid)
                          AND store_id IS NOT DISTINCT FROM CAST(:storeId AS uuid)
                          AND capability_id IS NOT DISTINCT FROM CAST(:capabilityId AS uuid)
                          AND status = 'ACTIVE'
                        """)
                .param("flagCode", flagCode)
                .param("scopeKind", scopeKind.name())
                .param("platformCode", platformCode)
                .param("marketplaceAccountId", marketplaceAccountId)
                .param("storeId", storeId)
                .param("capabilityId", capabilityId)
                .query(FeatureFlagRepository::map)
                .optional();
    }

    /** List flags by code and scope key with a keyset cursor. */
    public List<FeatureFlag> list(String afterFlagCode, String afterScopeKey, int limit) {
        return jdbc.sql("""
                        SELECT * FROM platform.feature_flag
                        WHERE (CAST(:afterFlagCode AS text) IS NULL
                              OR (flag_code, scope_key) > (:afterFlagCode, :afterScopeKey))
                        ORDER BY flag_code, scope_key
                        LIMIT :pageLimit
                        """)
                .param("afterFlagCode", afterFlagCode)
                .param("afterScopeKey", afterScopeKey)
                .param("pageLimit", limit)
                .query(FeatureFlagRepository::map)
                .list();
    }

    /** Count active flags scoped to one marketplace account. */
    public long countActiveByAccount(UUID marketplaceAccountId) {
        return jdbc.sql("""
                        SELECT count(*) FROM platform.feature_flag
                        WHERE marketplace_account_id = :marketplaceAccountId
                          AND status = 'ACTIVE'
                        """)
                .param("marketplaceAccountId", marketplaceAccountId)
                .query(Long.class)
                .single();
    }

    /** Count active flags scoped to one store. */
    public long countActiveByStore(UUID storeId) {
        return jdbc.sql("""
                        SELECT count(*) FROM platform.feature_flag
                        WHERE store_id = :storeId AND status = 'ACTIVE'
                        """)
                .param("storeId", storeId)
                .query(Long.class)
                .single();
    }

    private static FeatureFlag map(ResultSet row, int rowNumber) throws SQLException {
        return new FeatureFlag(
                row.getObject("id", UUID.class),
                row.getString("flag_code"),
                FlagKind.valueOf(row.getString("flag_kind")),
                FlagScopeKind.valueOf(row.getString("scope_kind")),
                row.getString("platform_code"),
                row.getObject("marketplace_account_id", UUID.class),
                row.getObject("store_id", UUID.class),
                row.getObject("capability_id", UUID.class),
                FlagState.valueOf(row.getString("state")),
                row.getString("description"),
                row.getString("reason"),
                RegistryStatus.valueOf(row.getString("status")),
                row.getTimestamp("created_at").toInstant(),
                row.getTimestamp("updated_at").toInstant(),
                row.getLong("version"));
    }
}
