from pathlib import Path
import copy,hashlib,json,re,subprocess,datetime,xml.etree.ElementTree as ET
root=Path('/Users/chzhengx/Code/personal/marketops-platform');out=Path('/tmp/slice3-source87-w8-final-preparation');oldroot=Path('/tmp/slice3-source87-measured-w6-review');oldfile=oldroot/'source87-individual-measured-review.json';old=json.loads(oldfile.read_text())
HEAD='9b6e6195f779bd80b1e8ed9c78d6ad9daa1a68af';TREE='eb4bce1333c87e4de762f6f42bbd3bcd392fec38';W6=old['measuredHead'];sha=lambda b:hashlib.sha256(b).hexdigest();write=lambda n,v:(out/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
cache={}
def raw(path,head=HEAD):
 key=(head,path)
 if key not in cache:cache[key]=subprocess.check_output(['/usr/bin/git','show',head+':'+path],cwd=root)
 return cache[key]
def source_identity(path):
 data=raw(path);prior=raw(path,W6)
 return {'path':path,'w8Commit':HEAD,'w8SourceSha256':sha(data),'w6Commit':W6,'w6SourceSha256':sha(prior),'sameBytesAsW6':data==prior}
def current_ref(path,method):
 data=raw(path);text=data.decode();locations=[text.count('\n',0,m.start())+1 for m in re.finditer(r'\bvoid\s+'+re.escape(method)+r'\s*\(',text)]
 if not locations:
  locations=[text.count('\n',0,m.start())+1 for m in re.finditer(r'\b'+re.escape(method)+r'\s*\(',text)]
 assert locations,(path,method)
 return {'path':path,'method':method,'w8SourceSha256':sha(data),'declarationOrReferenceLines':locations,'currentFinalExecutionStatus':'PENDING_FROZEN_W8_FULL_XML_BINDING'}
main='backend/marketops-server/src/main/java/com/mimococo/marketops/';test='backend/marketops-server/src/test/java/com/mimococo/marketops/';app=test+'advertisingefficiency/internal/application/'
calc=app+'AdvertisingCaseCalculationServiceTest.java';human=test+'AdvertisingHumanWorkflowIT.java';recon=app+'AdvertisingReconciliationWorkerTest.java';cap=app+'AdvertisingOrchestrationCapacityIT.java'
new_specs=[
(calc,'aPersistedMicrosecondOriginCannotGiveTheSameCalculationNegativeAge',24,'PURE_ACTUAL_CALCULATOR','At .123456789, persisted origin .123457 is the exact PG representation and has age0; existing critical cause remains P1.','CALCULATION_MICROSECOND_AGE'),
(calc,'microsecondRoundingAcrossASecondBoundaryStillRepresentsAgeZero',24,'PURE_ACTUAL_CALCULATOR','Origin at next whole second and asOf at .999999999 denote one persisted microsecond and produce age0, not -1 second.','CALCULATION_MICROSECOND_AGE'),
(calc,'aGenuinelyFutureCaseOriginRemainsUnknownInsteadOfZero',24,'PURE_ACTUAL_CALCULATOR','Origin .123458 exceeds exact .123457 representation, so value remains null with PRIORITY_POLICY_UNRESOLVED:CASE_AGE; it is not a zero-value safety fact.','CALCULATION_MICROSECOND_AGE'),
(calc,'anExistingCaseKeepsItsPositiveElapsedAge',24,'PURE_ACTUAL_CALCULATOR','A real129600-second interval remains1.5 days; the repair neither resets nor clamps positive exposure.','CALCULATION_MICROSECOND_AGE'),
(human,'staffedTaskAgeUsesTheExactPersistedMicrosecondOrigin',25,'REAL_POSTGRESQL_SYNTHETIC_TIMESTAMP_ORACLE','Actual PG round-up is asserted; public Case and direct Task reads agree at age0 with valid staffed profile/deadlines. A genuinely earlier read is absent; positive129600-second age remains.','TASK_SLO_MICROSECOND_AGE'),
(human,'unresolvedProfileTaskAgeUsesTheExactPersistedMicrosecondOrigin',25,'REAL_POSTGRESQL_SYNTHETIC_TIMESTAMP_ORACLE','Missing profile remains PROFILE_OR_CALENDAR_MISSING with null due time, while actual rounded-origin age is0; public/direct historical reads reject the genuinely future Task.','TASK_SLO_MICROSECOND_AGE'),
(recon,'oneNanosecondClockReversalIsUnknownAndBreachedInsteadOfZeroLatency',25,'ACTUAL_SWEEP_SERVICE_WITH_MOCKED_PORTS','After an already accepted fact, clock reverses1ns; captured trace latency is null and breach true. This is a clock decision test, not PostgreSQL throughput.','RECONCILIATION_EXACT_DURATION'),
(recon,'exactZeroLatencyIsMeasuredAndDoesNotBreach',25,'ACTUAL_SWEEP_SERVICE_WITH_MOCKED_PORTS','Zero Duration records0ms and does not breach.','RECONCILIATION_EXACT_DURATION'),
(recon,'exactFifteenMinuteLatencyDoesNotBreachTheInclusiveBound',25,'ACTUAL_SWEEP_SERVICE_WITH_MOCKED_PORTS','Exactly900seconds records900000ms without breach.','RECONCILIATION_EXACT_DURATION'),
(recon,'oneNanosecondBeyondFifteenMinutesBreachesBeforeMillisecondConversion',25,'ACTUAL_SWEEP_SERVICE_WITH_MOCKED_PORTS','900seconds+1ns records rounded900000ms but breach true; the control evaluates exact Duration before display/storage conversion.','RECONCILIATION_EXACT_DURATION'),
(cap,'declaredThousandObjectPortfolioMeetsAdvertisingSloAndRepairsDroppedCorrections',25,'REAL_POSTGRESQL_BOUNDED_ORCHESTRATION_MEASUREMENT','1000 UNVERIFIED native objects share one Variant/listing;200 seeded regression-containment oracles. Actual target refresh/Task/brief and dropped correction sweep are measured; API command count is0. This is not a mature Outcome or Provider command throughput benchmark.','CAPACITY_AND_REPLAY'),
(cap,'replayAndAnExpiredLeaseCannotSwallowANewerFactOrHideAnOldBreach',25,'REAL_POSTGRESQL_QUEUE_REPLAY','Clock base comes from PG clock_timestamp; exact accepted timestamp equality, expired-owner fencing, newer fact retention and existing old breach survive.','CAPACITY_AND_REPLAY'),
(cap,'sameAsOfTargetedAndSweepShareOneProjectionAndPolicyChangeWakesOnlyItsOrganization',25,'REAL_POSTGRESQL_COMPLETE_CALCULATION_REPLAY','Forces .123456789->.123457 for actual projected Case IDs; checks full calculation equality, stable Case IDs, zero Case age and true historical exclusion. Earlier unrelated preseeded Case remains legitimate and is excluded only from this new-origin oracle.','CAPACITY_AND_REPLAY')]
run_cache={};new_refs=[]
for path,method,n,layer,assertion,group in new_specs:
 rp=Path(f'/tmp/slice3-r1-final-controls-r{n}');receipt=json.loads((rp/'receipt.json').read_text());before=json.loads((rp/'source-before.json').read_text());after=json.loads((rp/'source-after.json').read_text());assert receipt['sourceStable'] and before==after
 xml=next(x for x in (rp/'reports').glob('TEST-*.xml')if x.name.endswith('.'+Path(path).stem+'.xml'));data=xml.read_bytes();suite=ET.fromstring(data);cases=suite.findall('testcase');found=[(i,c)for i,c in enumerate(cases)if c.get('name')==method or c.get('name','').startswith(method+'(')]
 assert found,(method,xml)
 assert all(not any(c.find(t)is not None for t in ['failure','error','skipped'])for _,c in found)
 assert before[path]==sha(raw(path)),(path,n)
 r=current_ref(path,method);r.update({'group':group,'specificAssertion':assertion,'proofLayer':layer,'targetedExecution':{'run':'R'+str(n),'receiptPath':str(rp/'receipt.json'),'receiptSha256':sha((rp/'receipt.json').read_bytes()),'command':receipt['command'],'wholeRunCounts':receipt['counts'],'wholeRunExitCode':receipt['exitCode'],'wholeRunAllPass':receipt['completeSelectedClassesPass'],'sourceStable':True,'sourceBeforeSha256':receipt['sourceBeforeSha256'],'sourceAfterSha256':receipt['sourceAfterSha256'],'testSourceMatchesW8':True,'xmlPath':str(xml),'xmlSha256':sha(data),'suiteDeclaredCounts':{k:suite.get(k)for k in ['tests','failures','errors','skipped']},'actualSuiteNodes':len(cases),'actualMatchedNodes':[{'nodeOrdinal':i,'name':c.get('name'),'classname':c.get('classname'),'timeSeconds':c.get('time'),'status':'PASS'}for i,c in found]},'boundary':'A specifically observed passing assertion in this historical targeted run, not a completed unselected W8 full-run claim.'});new_refs.append(r)
 runtime_paths={
  'CALCULATION_MICROSECOND_AGE':[main+'advertisingefficiency/internal/application/AdvertisingCaseCalculationService.java',main+'advertisingefficiency/internal/domain/AdPriorityPolicy.java',main+'advertisingefficiency/internal/domain/AdRankFactor.java'],
  'TASK_SLO_MICROSECOND_AGE':[main+'operationsworkflow/internal/application/AdvertisingTaskSloService.java',main+'operationsworkflow/internal/domain/StaffedResponseClock.java'],
  'RECONCILIATION_EXACT_DURATION':[main+'advertisingefficiency/internal/application/AdvertisingReconciliationWorker.java',main+'advertisingefficiency/internal/domain/AdvertisingSlo.java'],
  'CAPACITY_AND_REPLAY':[main+'advertisingefficiency/internal/application/AdvertisingCaseCalculationService.java',main+'advertisingefficiency/internal/application/AdvertisingCaseRefreshService.java',main+'advertisingefficiency/internal/application/AdvertisingTargetedWorker.java',main+'advertisingefficiency/internal/application/AdvertisingReconciliationWorker.java',main+'advertisingefficiency/internal/infrastructure/jdbc/AdvertisingEvidenceRepository.java']}[group]
 r['targetedExecution']['relevantRuntimeSourceBindings']=[]
 for runtime_path in runtime_paths:
  assert before[runtime_path]==sha(raw(runtime_path)),(runtime_path,n)
  r['targetedExecution']['relevantRuntimeSourceBindings'].append({'path':runtime_path,'measuredSourceSha256':before[runtime_path],'w8GitSourceSha256':sha(raw(runtime_path)),'sameExactBytes':True})
 run_cache[n]={'path':str(rp/'receipt.json'),'sha256':sha((rp/'receipt.json').read_bytes()),'wholeCounts':receipt['counts'],'exitCode':receipt['exitCode'],'sourceStable':True,'sourceBeforeSha256':receipt['sourceBeforeSha256'],'sourceAfterSha256':receipt['sourceAfterSha256'],'logSha256':receipt['logSha256']}
calc_ids={53,55,56,59,60,62,194,195,196};task_ids={60,64,67,68,69,195,196};recon_ids={70,71,195,196};capacity_ids={23,62,70,71,194,195,196}
impacts={
23:'The late/corrected-fact authority remains unchanged. R25 adds a representable database clock oracle so replay cannot spuriously reject an otherwise identical accepted timestamp; it does not renew source freshness or erase an older breach.',
53:'W8 corrects only the CASE_AGE derivation shared by deterministic calculation. Its full asOf replay must retain the same complete calculation and projected identities; lane resolver evidence and policy versions remain separate unchanged obligations.',
55:'The new genuine-future origin case explicitly retains a null rank value/reason. This supports unknown rank evidence, not a new permission to increase/decrease or a substitute for the existing independent unknown action tests.',
56:'A persisted origin rounded a fraction of a microsecond above Java asOf previously manufactured -1 second and could alter the accepted tuple on replay. W8 treats only the exact same representable origin as0; true future stays unknown and positive age stays1.5 days. P1 remains asserted.',
59:'The lane-specific tuple definitions and non-compensation tests are unchanged. W8 repairs the common age input before ranking; the new critical-lane age unit does not replace independent Data Repair/Optimization/Watch order assertions.',
60:'Canonical rank and response origin are calculated from persisted authority with asOf cutoffs. W8 precision repair cannot read a genuinely future Task or mutate its due time; it supplies no AI/personal-sort mutation permission. Existing cross-stream UI/security assertions remain necessary.',
62:'The new integration oracle selects the Case IDs actually written by the canonical refresh, rather than all synthetic rows sharing the object. Exact target/sweep output and identity equality are retained; earlier unrelated fixture rows do not imply duplicate canonical cause identity.',
64:'Acknowledgement and action remain separate event-derived deadlines. The added actual PG tests establish only that both SLO entry points use a nonnegative same-origin exposure age and deny genuinely future Task history; existing stage-progress tests remain the proof of stage distinction.',
67:'The repair changes timestamp representation handling, not firstRaised or reassignment history. New positive129600-second and genuine-future tests complement unchanged actual reassignment before/after database assertions; they do not stand in for those assertions.',
68:'Staffed coverage and external exposure remain independent fields. W8 prevents a same-origin -1-second display while retaining valid due times, missing-profile state and historical exclusion; existing out-of-coverage tests retain the actual active-harm label proof.',
69:'A missing profile still returns PROFILE_OR_CALENDAR_MISSING and no due-time assertion. The actual PG boundary now reports age0 only at the exact persisted origin, while earlier public/direct reads return absent; missing readiness cannot be relabeled on-time.',
70:'R25 demonstrates the declared1000-object UNVERIFIED diagnostic/Case/Task orchestration workload:200 explicit containment oracles, one shared Variant/listing, zero commands. It does not measure1000 mature Outcome calculations, a verified Optimization portfolio, multi-store cardinality or transport throughput. The separate scoped Outcome IT proves correctness, not this throughput. Exact sweep Duration tests retain unknown on -1ns, allow900s and breach900s+1ns before millisecond conversion.',
71:'R25 measures complete sweep of the declared1000-object portfolio and repairs one dropped canonical correction with reported hourly margin. Exact full asOf calculation replay now deliberately exercises PG microsecond round-up. Restoring state does not remove an old breach; elapsed control is evaluated as Duration, not rounded milliseconds.',
169:'The new timing/orchestration tests remain isolated synthetic engineering tests with production writes disabled. Their zero-command UNVERIFIED capacity path must not be described as successful real or fixture Provider throughput.',
174:'A diagnostic capacity pass does not discharge future30-day/Settled obligations. Existing stage-specific canonical Outcome tests and scheduling authority remain the source contribution; the new benchmark carries no mature Outcome load.',
194:'R25 strict queue replay and full-calculation identity comparisons close the observed precision-specific replay failure. Original Case/Task concurrency and Outcome revision/attestation replay assertions remain required; no single capacity pass proves all command/reservation/audit ledgers.',
195:'New evidence layers stay explicit: four actual-calculator units, two real-PG SLO timestamp oracles, four actual-sweep tests with mocked ports, and three real-PG bounded orchestration cases. Neither the mock sweep nor the UNVERIFIED benchmark substitutes for broader current full, browser, authority or mature Outcome proof.',
196:'The added adverse inputs are concrete: +122ns persisted-origin discrepancy, a genuinely later microsecond, -1ns clock reversal and900s+1ns hard-bound excess. The asserted unknown/zero/breach distinctions are not blanket clamping or relaxed limits; the existing transmission/lease/late-fact fault matrix remains complementary.',
199:'W6 historical proofs are preserved verbatim with their measured identity. W7 failed CI, R24 partial failure and R25 complete targeted result are separate sources. The running W8 full XML is not read or bound until completion, and the eventual exact CI/Git/Controller judgment remains Parent-owned.'}
criteria=[];all_refs={};all_sources={}
for c in old['criteria']:
 num=int(c['criterionId'].split('-')[-1]);review=copy.deepcopy(c['individualEngineeringReview']);refs=[]
 for q in c['specificNamedAssertionEvidence']:
  ref=current_ref(q['path'],q['method']);refs.append(ref);all_refs[(ref['path'],ref['method'])]=ref
 selected=[x for x in new_refs if (x['group']=='CALCULATION_MICROSECOND_AGE'and num in calc_ids)or(x['group']=='TASK_SLO_MICROSECOND_AGE'and num in task_ids)or(x['group']=='RECONCILIATION_EXACT_DURATION'and num in recon_ids)or(x['group']=='CAPACITY_AND_REPLAY'and num in capacity_ids)]
 for x in selected:
  if (x['path'],x['method'])not in {(a['path'],a['method'])for a in refs}:refs.append(current_ref(x['path'],x['method']))
  all_refs[(x['path'],x['method'])]=current_ref(x['path'],x['method'])
 source_paths={x['path']for x in c['implementationBasis']}
 if num in calc_ids:source_paths.add(main+'advertisingefficiency/internal/application/AdvertisingCaseCalculationService.java')
 if num in task_ids:source_paths.add(main+'operationsworkflow/internal/application/AdvertisingTaskSloService.java')
 if num in recon_ids:source_paths.add(main+'advertisingefficiency/internal/application/AdvertisingReconciliationWorker.java')
 sources=[]
 for path in sorted(source_paths):
  v=source_identity(path);sources.append(v);all_sources[path]=v
 if num in [70,71]:
  review['positiveAssertions']='Actual scoped Outcome evaluation and replay assertions establish correctness. The separately measured R25 capacity case exercises1000 UNVERIFIED one-member objects, real refresh/projection/Task/brief paths,200 seeded containment oracles and one dropped official correction. Actual local timing is attached with its dataset and resources; it is not per-trigger-class or mature Outcome throughput.'
  review['proofLimits']=['The capacity profile is UNVERIFIED, API commands are asserted0, and no mature Outcome workload or Provider transport throughput is measured.','Do not infer higher-cardinality affected sets, multi-store/organization workload, fully qualified Optimization economics or future maturity backlog capacity from this declared dataset.','Final unselected W8 full capacity and exact remote CI must be bound after completion; R25 remains targeted evidence.']
 review['assessment']='INDIVIDUAL_SOURCE_ENGINEERING_PREPARATION; W8_UNSELECTED_FULL_BINDING_PENDING'
 review['requiredBeforeClosure']='Bind these exact current W8 assertions to frozen completed unselected full XML/capacity and required cross-stream/CI artifacts, then apply individual engineering judgment. No aggregate count or historical pass automatically accepts this criterion.'
 criteria.append({'criterionId':c['criterionId'],'acceptedExact':c['acceptedExact'],'acceptedContractLine':c['acceptedContractLine'],'status':'PENDING_W8_UNSELECTED_FULL_AND_EXACT_CI_BINDING','individualEngineeringReview':review,'w8SpecificEngineeringReason':review['individualEngineeringReason']+(' '+impacts[num]if num in impacts else ''),'w8ExplicitDeltaAssessment':impacts.get(num,'No mapped runtime or authority behavior is changed for this accepted obligation by the W7-to-W8 precision/isolation patch; source hashes below identify whether a containing file changed. The preserved criterion-specific reasoning and positive/adverse scope remain the assessment basis.'),'currentImplementationBasis':sources,'currentRequiredNamedAssertions':refs,'newRepairTargetedAssertionRefs':[{'path':x['path'],'method':x['method'],'group':x['group'],'evidenceFile':'new-w8-assertion-reference-plan.json'}for x in selected],'priorW6Review':{'file':'historical-source87-measured-w6-review.json','criterionId':c['criterionId'],'measuredHead':W6,'measuredTree':old['measuredTree'],'statusIsHistoricalOnly':True},'proofLayerAndCrossStreamLimits':review['proofLimits'],'currentFinalExecutionEvidence':None,'controllerVerdict':None})
# Retain the already owned cross-stream contributions without relabeling W6 execution.
cross=[]
for c in old['crossStreamContributions']:
 refs=[]
 def walk(v):
  if isinstance(v,dict):
   if isinstance(v.get('path'),str)and v['path'].endswith('.java')and isinstance(v.get('method'),str):refs.append(current_ref(v['path'],v['method']))
   for x in v.values():walk(x)
  elif isinstance(v,list):
   for x in v:walk(x)
 walk(c)
 for a in refs:all_refs[(a['path'],a['method'])]=a
 cross.append({'criterionIds':c.get('criterionIds'),'findingIds':c.get('findingIds'),'primaryReviewOwner':c.get('primaryReviewOwner'),'historicalW6Contribution':copy.deepcopy(c),'w8RequiredNamedAssertions':list({(a['path'],a['method']):a for a in refs}.values()),'status':'PENDING_W8_FULL_BINDING_AND_PRIMARY_OWNER_REVIEW'})
capdir=Path('/tmp/slice3-r1-final-controls-r25/capacity');capacity=json.loads((capdir/'advertising-capacity-receipt.json').read_text());data=json.loads((capdir/'advertising-capacity-dataset.json').read_text())
capacity_review={'historicalTargetedRun':'R25','receiptSha256':sha((capdir/'advertising-capacity-receipt.json').read_bytes()),'datasetSha256':sha((capdir/'advertising-capacity-dataset.json').read_bytes()),'sourceInputSha256':sha((capdir/'advertising-capacity-source-inputs.json').read_bytes()),'exactMeasuredScope':{'organizations':1,'stores':1,'nativeObjects':1000,'sharedProductVariants':1,'sharedListings':1,'membersPerAffectedSet':1,'seededRegressionContainmentObjects':200,'semanticProfile':'UNVERIFIED','apiCommandCountAsserted':0,'matureOutcomeThroughput':'NOT_MEASURED; no mature Outcome workload is generated by this benchmark','providerIo':'NONE','productionWriteEnabled':False,'inputRowCounts':{k:len(v)for k,v in data['canonicalInputRows'].items()}},'actualR25Measurements':{k:capacity[k]for k in ['targeted','targetedWallMillis','workerPasses','sweepWallMillis','hourlyMarginMillis','responsibilityTasks','droppedLateCorrectionRecovered']},'runtime':capacity['runtime'],'runtimeResourceReceiptSha256':capacity['identities']['runtimeResourceReceiptSha256'],'notClaimed':['per-trigger-class P95 distribution','1000 mature Outcome calculations','API/Manual command throughput','real Provider capacity','fully qualified Optimization portfolio','multi-organization or large affected-set economics'],'currentW8FullCapacityEvidence':None,'currentStatus':'PENDING_FINAL_W8_UNSELECTED_RUN_BINDING'}
(out/'historical-source87-measured-w6-review.json').write_bytes(oldfile.read_bytes())
write('new-w8-assertion-reference-plan.json',new_refs);write('current-w8-required-methods.json',list(all_refs.values()));write('current-w8-source-identities.json',list(all_sources.values()));write('capacity-proof-boundary.json',capacity_review);write('historical-targeted-run-bindings.json',run_cache)
result={'kind':'SOURCE87_W8_INDIVIDUAL_ENGINEERING_PREPARATION','generatedAtUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'head':HEAD,'tree':TREE,'scope':'Existing87 criteria and source-owned AC131/F012 contributions only. Existing substantive individual reasons preserved; precision and capacity boundaries explicitly updated.','criteriaCount':len(criteria),'historicalW6Proof':{'originalPath':str(oldfile),'sha256':sha(oldfile.read_bytes()),'localPreservedCopy':'historical-source87-measured-w6-review.json','measuredHead':W6,'notRelabeledAsW8':True},'criteria':criteria,'crossStreamContributions':cross,'currentSourceIdentityFile':'current-w8-source-identities.json','currentRequiredMethodFile':'current-w8-required-methods.json','newNamedAssertionFile':'new-w8-assertion-reference-plan.json','targetedRunBindingsFile':'historical-targeted-run-bindings.json','capacityBoundaryFile':'capacity-proof-boundary.json','fullRunReadBoundary':'No running W8 receipt/XML/JAR/coverage/capacity or live target report was read; only completed R24/R25 reports and immutable committed W8 Git blobs were used.','w8UnselectedFullEvidence':None,'status':'PENDING_COMPLETED_FROZEN_W8_FULL_BINDING_AND_FINAL_INDIVIDUAL_JUDGMENT','controllerVerdict':None}
assert len(criteria)==87 and len({c['criterionId']for c in criteria})==87
write('source87-w8-prepared-review.json',result)
files=sorted(x for x in out.iterdir()if x.is_file()and x.name!='manifest.json');write('manifest.json',{'generatedAtUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'files':[{'path':f.name,'bytes':f.stat().st_size,'sha256':sha(f.read_bytes())}for f in files]})
print(json.dumps({'criteria':87,'requiredUniqueMethods':len(all_refs),'newRepairBindings':len(new_refs),'reviewSha256':sha((out/'source87-w8-prepared-review.json').read_bytes()),'manifestSha256':sha((out/'manifest.json').read_bytes())},indent=2))
