#!/usr/bin/env python3
"""Offline exact-source raw security crosscheck; findings stay open, no closure mutation."""
import argparse,collections,datetime,hashlib,json,subprocess,zipfile
from pathlib import Path
if not __debug__: raise RuntimeError('Optimized Python disables required evidence checks')
ap=argparse.ArgumentParser();ap.add_argument('--capture',type=Path,required=True);ap.add_argument('--repo',type=Path,required=True);ap.add_argument('--out',type=Path,required=True);a=ap.parse_args();C=a.capture.resolve();O=a.out.resolve();assert O.is_relative_to(Path('/tmp').resolve()) and not O.exists();O.mkdir(parents=True)
sha=lambda b:hashlib.sha256(b).hexdigest()
def read(p):return json.loads(Path(p).read_text())
def ref(p):p=Path(p).resolve();return {'path':str(p),'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size}
def checked(e):p=Path(e['path']);assert ref(p)['sha256']==e['sha256'];return p
def pages(name):return [x for page in read(C/name)for x in page]
cap=read(C/'CAPTURE-RECEIPT.json');assert cap['phase']=='completed' and cap['failure']is None and cap['inputsStable']is True
index=read(C/'INDEX.json');[checked(e)for e in index['files']];H=cap['head'];M=cap['testedMerge'];baseline=read(checked(cap['baselineSecurity']));run=read(C/'security-run.json');jobs=read(C/'security-jobs.json')['jobs'];aggregate=[c for c in read(C/'source-check-runs.json')['check_runs']if c['name']=='CodeQL'];assert len(aggregate)==1
annotations=pages('aggregate-'+str(aggregate[0]['id'])+'-annotations-pages.json');assert len(annotations)==aggregate[0]['output']['annotations_count']
criteria={'officialRunSuccess':run['status']=='completed'and run['conclusion']=='success','allThreeJobsSuccess':len(jobs)==3 and all(j['status']=='completed'and j['conclusion']=='success'for j in jobs),'aggregateCodeQLSuccess':aggregate[0]['head_sha']==H and aggregate[0]['conclusion']=='success'}
assert all(criteria.values()),'An actual Security context did not succeed; raw retained, no success review.'
rawlogs=zipfile.ZipFile(C/'security-run-logs.zip');assert rawlogs.testzip()is None;logidx=read(C/'RAW-LOG-MEMBER-INDEX.json');checkout=[];build=[];upload=[]
for e in logidx['members']:
 b=rawlogs.read(e['member']);assert sha(b)==e['sha256'] and format(rawlogs.getinfo(e['member']).CRC,'08x')==e['crc32'];lines=b.decode('utf-8','replace').splitlines()
 if e['member'].endswith('/2_Checkout repository.txt'):
  relevant=[{'line':i+1,'text':line}for i,line in enumerate(lines)if M in line or 'HEAD is now at '+M[:7]in line];assert relevant and any(M in x['text']for x in relevant);checkout.append({'member':e,'actualLines':relevant})
 if e['member'].startswith('codeql-java/') and any('[INFO] BUILD SUCCESS'in x for x in lines):build.append({'member':e,'actualBuildSuccessLines':[i+1 for i,x in enumerate(lines)if '[INFO] BUILD SUCCESS'in x]})
 if any('Successfully uploaded results'in x for x in lines):upload.append({'member':e,'actualUploadLines':[i+1 for i,x in enumerate(lines)if 'Successfully uploaded results'in x]})
assert len(checkout)==3 and build and len(upload)>=2
opened=pages('open-alerts-pages.json');dismissed=pages('dismissed-alerts-pages.json');alerts={x['number']:x for x in opened+dismissed};assert len(alerts)==len(opened)+len(dismissed) and all(x['most_recent_instance']['commit_sha']==M for x in alerts.values())
results=[];sarifcounts=[]
for name in ['java.sarif.json','typescript.sarif.json']:
 p=C/name;document=read(p);count=0
 for runpart in document['runs']:
  assert all(v['revisionId']==M for v in runpart['versionControlProvenance'])
  for r in runpart['results']:
   count+=1;no=r['properties']['github/alertNumber'];al=alerts[no];loc=r['locations'][0]['physicalLocation'];reg=loc['region'];auth=al['most_recent_instance']['location'];assert r['ruleId']==al['rule']['id'] and loc['artifactLocation']['uri']==auth['path']
   for sk,ak in [('startLine','start_line'),('endLine','end_line'),('startColumn','start_column'),('endColumn','end_column')]:assert reg.get(sk)==auth.get(ak)
   results.append({'number':no,'ruleId':r['ruleId'],'state':al['state'],'exactLocation':auth,'sarif':ref(p)})
 analysis=[x for x in cap['selectedAnalyses']if x['category']==('/language:java-kotlin'if name=='java.sarif.json'else '/language:javascript-typescript')];assert len(analysis)==1 and analysis[0]['results_count']==count; sarifcounts.append({'file':ref(p),'actualResults':count,'analysisId':analysis[0]['id'],'sarifId':analysis[0]['sarif_id'],'analysisKey':analysis[0]['analysis_key']})
assert collections.Counter(x['number']for x in results)==collections.Counter(alerts.keys())
prior=read(checked(baseline['openAlerts']['triage']));priorrows={x['number']:x for x in prior['findings']};currentrows={x['number']:x for x in opened};sourcecache={};expressionchecks=[]
for no,al in currentrows.items():
 loc=al['most_recent_instance']['location'];path=loc['path']
 if path not in sourcecache:sourcecache[path]=subprocess.check_output(['git','--no-replace-objects','show',H+':'+path],cwd=a.repo)
 b=sourcecache[path];lines=b.decode().splitlines();segment=lines[loc['start_line']-1:loc['end_line']];segment[0]=segment[0][loc['start_column']-1:];segment[-1]=segment[-1][:loc['end_column']-(loc['start_column']if len(segment)==1 else 1)];eh=sha('\n'.join(segment).encode());old=priorrows.get(no)
 expressionchecks.append({'number':no,'sourcePath':path,'currentWholeSourceSha256':sha(b),'currentExpressionSha256':eh,'priorWholeSourceSha256':old.get('currentSourceSha256')if old else None,'priorExpressionSha256':old.get('currentFlaggedExpressionSha256')if old else None,'samePriorExpression':old is not None and eh==old['currentFlaggedExpressionSha256'],'level':al['rule']['severity'],'securitySeverity':al['rule'].get('security_severity_level'),'scope':'A same expression and source permit prior triage context to be reviewed, not automatic dismissal.'})
newhigh=[x['number']for x in opened if x['rule'].get('security_severity_level')in ['high','critical'] and (x['number']not in priorrows or not next(c for c in expressionchecks if c['number']==x['number'])['samePriorExpression'])];criteria['noNewSecurityHighOrCritical']=not newhigh
historical=read(checked(baseline['historicalDismissedHigh']['reconciliation']));oldhigh={f['number']:f for f in historical['findings']};dismissedchecks=[]
for f in dismissed:
 old=oldhigh.get(f['number']);loc=f['most_recent_instance']['location'];b=subprocess.check_output(['git','--no-replace-objects','show',H+':'+loc['path']],cwd=a.repo);dismissedchecks.append({'number':f['number'],'securitySeverity':f['rule'].get('security_severity_level'),'state':f['state'],'dismissedAt':f['dismissed_at'],'dismissedReason':f['dismissed_reason'],'dismissedCommentSha256':sha((f['dismissed_comment']or'').encode()),'sourceSha256':sha(b),'priorKnown':old is not None,'sameHistoricalSource':old is not None and sha(b)==old['currentSourceSha256'],'raw':ref(C/'dismissed-alerts-pages.json')})
default=pages('default-main-dependabot-pages.json');dep=read(C/'dependency-diff.json');addedv=sum(len(x.get('vulnerabilities',[]))for x in dep if x['change_type']=='added');criteria['noNewDependencyVulnerabilityRecords']=addedv==0
out={'kind':'FINAL_CONTAINING_COMMIT_SECURITY_RAW_REVIEW_CANDIDATE','recordedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'sourceHead':H,'sourceTree':cap['tree'],'testedMerge':M,'testedMergeTree':read(C/'tested-merge-commit.json')['tree']['sha'],'testedMergeParents':[cap['base'],H],'productSourceHead':cap['productSourceHead'],'productInventory':cap['productInventory'],'sourceComparison':ref(C/'PRODUCT-TO-FINAL-CI-SOURCE-COMPARISON.json'),'capture':ref(C/'CAPTURE-RECEIPT.json'),'criteria':criteria,'run':cap['run'],'jobs':cap['jobs'],'aggregate':aggregate[0],'actualAggregateAnnotationCount':len(annotations),'actualCheckoutProof':checkout,'actualJavaBuildProof':build,'actualSarifUploadProof':upload,'sarifCounts':sarifcounts,'sarifAlertLocationMatches':results,'actualOpenCount':len(opened),'actualOpenLevelCounts':dict(collections.Counter(x['rule']['severity']for x in opened)),'openDelta':{'added':sorted(set(currentrows)-set(priorrows)),'removed':sorted(set(priorrows)-set(currentrows)),'newHighOrCritical':newhigh,'expressionChecks':expressionchecks},'historicalDismissedFindings':dismissedchecks,'defaultMainDependencyAlerts':{'actualCount':len(default),'severityCounts':dict(collections.Counter(x['security_advisory']['severity']for x in default)),'raw':ref(C/'default-main-dependabot-pages.json'),'scope':'Default branch only; not the PR source audit.'},'actualPrDependencyDelta':{'addedVulnerabilityRecords':addedv,'raw':ref(C/'dependency-diff.json')},'baselineSecurity':cap['baselineSecurity'],'publicationReview':'PENDING_EXACT_RAW_PATTERN_SCAN_AND_PER_HIT_TRIAGE','scopeReview':'REQUIRES_ROOT_REVIEW_OF_ANY_DELTA_OR_CHANGED_CONTEXT','automaticGatePassClaimMade':False,'engineeringClosureClaimMade':False,'controllerApprovalClaimMade':False,'alertsModifiedOrDismissed':False,'productionWriteEnabled':False,'limits':['Final CI actual source/run is distinct from original02e local runs and evidence-onlyD executions.','No0quality or0rawHIGH claim. Historical dismissed HIGH/default-main HIGH remain separate.','Missing/failed contexts, changed source, unmatched SARIF locations or unreviewed changed expressions cannot be silently promoted.','Publication raw-scan remains separately mandatory; official rule help is triaged by exact bytes.']};(O/'SECURITY-RAW-REVIEW-CANDIDATE.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'result':ref(O/'SECURITY-RAW-REVIEW-CANDIDATE.json'),'allCriteriaObserved':all(criteria.values()),'rootReviewStillRequired':True}))
