build.artifact=marketops-server
build.gitCommit=32b307c648d16f2ecb7f0074e615e78e95ed4121
build.group=com.mimococo.marketops
build.name=MarketOps Server
build.time=2026-01-01T00\:00\:00Z
build.version=0.1.0-SNAPSHOT
