from pathlib import Path
import json,hashlib,datetime,copy,subprocess,xml.etree.ElementTree as ET
base=Path('/tmp/slice3-source-w6-review/source-87-engineering-review-w6.json');original=base.read_bytes();draft=json.loads(original);out=Path('/tmp/slice3-source87-measured-w6-review');out.mkdir(exist_ok=True);runDir=Path('/tmp/slice3-r1-full-clean-w6-3ed3f4c').resolve();receiptPath=runDir/'run-receipt.json';receipt=json.loads(receiptPath.read_text());indexPath=Path('/tmp/slice3-r1-named-junit-w6.json');index=json.loads(indexPath.read_text());joinPath=Path('/tmp/slice3-r1-individual-backend-join-w6.json');join=json.loads(joinPath.read_text());deltaPath=Path('/tmp/slice3-r1-w6-w7-input-delta/receipt.json');delta=json.loads(deltaPath.read_text());sha=lambda b:hashlib.sha256(b).hexdigest();now=datetime.datetime.now(datetime.timezone.utc).isoformat();head='3ed3f4c87c336cb07188e470528f328358fb279f'
assert receipt['completePass'] and receipt['mavenExitCode']==0 and receipt['head']==head and receipt['backendSourceStable'] and receipt['everyActualTestcaseNodePassed']
assert receipt['actualTestcaseNodeCounts']=={'rawTestcaseNodes':2472,'declaredTests':2471,'actualFailures':0,'actualErrors':0,'actualSkipped':0}
assert receipt['head']==index['runIdentity']['head']==join['measuredHead'];assert index['runReceipt']['sha256']==sha(receiptPath.read_bytes())==join['fullRunReceiptSha256'];assert all(r['exactBytesUnchanged'] for r in delta['sourceBuildMigrationAndWorkflowInputs'])
sourcePath=Path(index['sourceManifest']['path']).resolve();sources=json.loads(sourcePath.read_text());assert sha(sourcePath.read_bytes())==receipt['backendSourceBeforeSha256']==receipt['backendSourceAfterSha256'];named={(r['path'],r.get('method')):r for r in index['references']};reportCache={};bindings={};sourceBindings={};sourceCache={}
def measured_source(path):
 if path in sourceBindings:return sourceBindings[path]
 data=subprocess.check_output(['/usr/bin/git','show',head+':'+path]);actual=sha(data);measured=sources.get(path)
 if path.startswith('backend/marketops-server/') and measured is not None:assert actual==measured
 result={'path':path,'exactMeasuredHead':head,'gitObjectBytesSha256':actual,'archivedSourceManifestSha256':measured,'matchesMeasuredSourceManifest':actual==measured if measured else None,'boundary':'Exact W6 Git bytes match completed full-run source manifest.' if measured else 'Outside the backend manifest; source/Git hash retained, requires corresponding artifact/governance proof.'};sourceBindings[path]=result;return result

def bind_method(path,method):
 key=(path,method)
 if key in bindings:return bindings[key]
 if key not in named:
  # This existing cross-stream qualifier is intentionally absent from the central AC map;
  # independently bind its two exact parameterized nodes in the already frozen report.
  assert path.endswith('/AdvertisingCrossDomainIsolationIT.java') and method=='descriptiveListingFieldsDoNotInventNewMaterialityThresholds'
  report=next(x for x in index['reportInventory'] if x['path'].endswith('AdvertisingCrossDomainIsolationIT.xml'));rp=Path(report['path']);data=rp.read_bytes();assert sha(data)==report['sha256'];rt=ET.fromstring(data);matches=[]
  fqcn='com.mimococo.marketops.AdvertisingCrossDomainIsolationIT'
  for so,suite in enumerate(rt.iter('testsuite')):
   for ordinal,case in enumerate(suite.findall('testcase')):
    if case.get('classname')==fqcn and case.get('name') in [method+'(String)[1]',method+'(String)[2]']:
     matches.append({'id':sha((report['sha256']+':'+str(so)+':'+str(ordinal)).encode()),'reportPath':str(rp),'reportSha256':report['sha256'],'phase':'failsafe','suiteName':suite.get('name'),'suiteOrdinal':so,'testcaseOrdinal':ordinal,'rawName':case.get('name'),'rawClassname':case.get('classname'),'status':'PASSED','seconds':case.get('time')})
  assert len(matches)==2;source=measured_source(path)
  r={'id':'SUPPLEMENTAL_FROZEN_XML:'+method,'path':path,'method':method,'matchStatus':'EXACT_FROZEN_XML_CASES_DIRECTLY_MATCHED','matches':matches,'sourceIdentity':{'measuredSha256':source['gitObjectBytesSha256']},'measuredDeclarations':[{'name':method,'owner':fqcn,'line':225,'signatureSource':'(String descriptive)','source':'Exact W6 Git declaration and frozen parameterized XML names; not claimed as a central index reference.'}]}
 else:r=named[key]
 assert r['matchStatus'] in ['EXACT_JUNIT_CASES_MATCHED','EXACT_FROZEN_XML_CASES_DIRECTLY_MATCHED'];source=measured_source(path);assert source['matchesMeasuredSourceManifest'] is True and r['sourceIdentity']['measuredSha256']==source['gitObjectBytesSha256']
 cases=[]
 for m in r['matches']:
  p=Path(m['reportPath']).resolve();assert p.is_relative_to(runDir/'artifacts'),p
  if str(p) not in reportCache:
   data=p.read_bytes();assert sha(data)==m['reportSha256'];root=ET.fromstring(data);reportCache[str(p)]={'sha':sha(data),'root':root}
  rr=reportCache[str(p)];assert rr['sha']==m['reportSha256'];suites=list(rr['root'].iter('testsuite'));suite=suites[m['suiteOrdinal']];case=suite.findall('testcase')[m['testcaseOrdinal']];assert case.get('name')==m['rawName'] and case.get('classname')==m['rawClassname'];assert not any(case.find(k) is not None for k in ['failure','error','skipped']);assert m['status']=='PASSED'
  cases.append({'reportArchiveMember':str(p.relative_to(runDir)),'rawXmlSha256':m['reportSha256'],'suiteName':m['suiteName'],'suiteOrdinal':m['suiteOrdinal'],'testcaseOrdinal':m['testcaseOrdinal'],'rawClassname':m['rawClassname'],'rawName':m['rawName'],'phase':m['phase'],'seconds':m['seconds'],'observedStatus':'PASSED','independentFrozenXmlCheck':'SHA, suite ordinal, testcase ordinal, exact classname/name and absent failure/error/skipped child verified by this review.','namedIndexReferenceId':r['id'],'namedIndexCaseId':m['id']})
 result={'path':path,'method':method,'exactSource':source,'measuredDeclarations':r['measuredDeclarations'],'namedReferenceId':r['id'],'namedIndexMatchStatus':r['matchStatus'],'observedInvocations':cases,'observedInvocationCount':len(cases),'executionAssessment':'NAMED_METHOD_INVOCATIONS_PASS_ON_COMPLETED_W6_SOURCE','semanticBoundary':'This is actual method execution; the criterion-specific positive/negative scope and engineering reason separately determine the extent of support.'};bindings[key]=result;return result

criteria=[]
for c in draft['criteria']:
 row=copy.deepcopy(c);row['previousDraftStatus']=row['status'];row['status']='MEASURED_BACKEND_ASSERTIONS_RECONCILED_FOR_INDIVIDUAL_ENGINEERING_REVIEW';actual=[]
 for test in row['specificNamedAssertionEvidence']:
  b=bind_method(test['path'],test['method']);test['completedW6Binding']=b;test['w6VerificationStatus']='NAMED_METHOD_INVOCATIONS_PASSED_IN_COMPLETED_W6_FULL_RUN';actual.append({'path':test['path'],'method':test['method'],'namedReferenceId':b['namedReferenceId'],'invocations':b['observedInvocationCount'],'proofBoundary':test.get('proofBoundary')})
 for src in row['implementationBasis']:src['completedW6SourceIdentity']=measured_source(src['path'])
 reason=row['individualEngineeringReview'];row['individualMeasuredEngineeringAssessment']={'acceptedClaim':row['acceptedExact'],'positiveOrNormalScopeActuallyReviewed':reason['positiveAssertions'],'negativeOrAdverseScopeActuallyReviewed':reason['negativeAssertions'],'engineeringReasonAppliedToMeasuredSource':reason['individualEngineeringReason'],'measuredNamedAssertions':actual,'observedResult':'Every listed named method and its matched parameterized/nested invocations passed the exact frozen W6 XML checks.' if actual else 'This criterion is an artifact/Git/governance obligation; no unrelated Java testcase is substituted.','proofLimitsRetained':reason['proofLimits'],'assessmentBoundary':'Passing the exact named assertions now supplies the execution evidence for the already explicit individual engineering reasoning. It does not enlarge that reasoning, replace other stream contributions or count this row as full acceptance.','primaryParentAdjudicationStillRequired':True,'controllerVerdict':None}
 if not actual:row['status']='ARTIFACT_AND_GOVERNANCE_RECONCILIATION_REQUIRES_PARENT_EVIDENCE'
 row['w6ToW7Applicability']={'receipt':str(deltaPath),'receiptSha256':sha(deltaPath.read_bytes()),'measuredHead':head,'publishedHead':delta['publishedHead'],'backendBuildAndWorkflowInputsExactUnchanged':True,'limit':'This remains a W6 local full measurement. The exact unchanged-input proof supports applicability to W7 backend code; it does not relabel the run as a W7 CI execution.'}
 criteria.append(row)
contributions=copy.deepcopy(draft['crossStreamContributions'])
for c in contributions:
 c['previousDraftStatus']=c.get('status');c['status']='CURRENT_BACKEND_SINK_ASSERTIONS_MEASURED_PASS_PRIMARY_OWNER_ADJUDICATION_PENDING'
 for r in c.get('sourceReferences',[]):
  if r.get('path'):r['completedW6SourceIdentity']=measured_source(r['path'])
 for r in c.get('testReferences',[]):
  methods=r.get('methods') or ([r['method']] if r.get('method') else [])
  r['completedW6Bindings']=[bind_method(r['path'],m) for m in methods]
 c['currentExecutionBoundary']='The named AC131 cross-domain/Manual and F012 retry-worker methods now have actual completed W6 raw XML/source bindings. Their historical R20/R21 causality and synthetic Provider limits remain; no primary-owner or Controller verdict is supplied here.'
refs=sorted(bindings.values(),key=lambda x:(x['path'],x['method']));uniqueCaseKeys={(m['rawXmlSha256'],m['suiteOrdinal'],m['testcaseOrdinal']) for r in refs for m in r['observedInvocations']};checks={'kind':'INDEPENDENT_FROZEN_XML_BINDING_CHECK','generatedAtUTC':now,'completedRunReceipt':str(receiptPath),'completedRunReceiptSha256':sha(receiptPath.read_bytes()),'fullObservedXmlNodes':2472,'fullDeclaredTests':2471,'fullDeclarationMismatchPreserved':receipt['suiteDeclarationMismatches'],'uniqueSourceAndMethodBindings':len(refs),'supplementalFrozenXmlBindingsNotInCentralIndex':[r['method'] for r in refs if r['namedIndexMatchStatus']=='EXACT_FROZEN_XML_CASES_DIRECTLY_MATCHED'],'uniqueReferencedXmlReports':len(reportCache),'uniqueReferencedCaseNodes':len(uniqueCaseKeys),'allReferencedObservedCaseNodesPassed':True,'allReferencedJavaSourceBytesMatchCompletedSourceManifest':True,'readScope':'Only /tmp frozen full-run artifacts and exact W6 Git blobs; no live target XML read, no repository writes.','controllerVerdict':None}
result={'kind':'SOURCE87_MEASURED_INDIVIDUAL_ENGINEERING_REVIEW_W6_APPLICABLE_W7','generatedAtUTC':now,'scope':draft['scope'],'criteriaCount':87,'measuredHead':head,'measuredTree':receipt['tree'],'publishedHead':delta['publishedHead'],'publishedTree':delta['publishedTree'],'inputDraft':{'path':str(base),'sha256':sha(original)},'sourceShard':draft['sourceShard'],'inputs':{'fullReceipt':{'path':str(receiptPath),'sha256':sha(receiptPath.read_bytes())},'namedIndex':{'path':str(indexPath),'sha256':sha(indexPath.read_bytes())},'individualJoin':{'path':str(joinPath),'sha256':sha(joinPath.read_bytes())},'backendSourceManifest':{'path':str(sourcePath),'sha256':sha(sourcePath.read_bytes())},'w6W7Delta':{'path':str(deltaPath),'sha256':sha(deltaPath.read_bytes())}},'criteria':criteria,'crossStreamContributions':contributions,'methodExecutionEvidenceFile':'source-method-xml-bindings.json','sourceIdentityFile':'source-identities.json','independentVerification':checks,'overallStatus':'INDIVIDUAL_ENGINEERING_INPUTS_READY_NO_OVERALL_ACCEPTANCE_OR_CONTROLLER_VERDICT','remainingGlobalBoundary':['Parent owns W7 backend CI/provenance reconciliation and aggregate final assessment; no all-CI-complete claim is made here.','AC199 requires actual final artifact/Git/governance/accepted-authority evidence rather than arbitrary Java methods.','Real Provider business outcomes/ongoing maturity/Gate-E expansion remain governed obligations; synthetic passing paths do not approve production writes.'],'semanticGapAssessment':'No new missing named backend assertion or current-source execution failure was found in the already bounded87-criterion scope. Each individual positive/negative argument and its explicit limits remain visible for Parent final judgment; external/UI/control/governance contributions are retained instead of inferred from total2472.','controllerVerdict':None}
(out/'source87-individual-measured-review.json').write_text(json.dumps(result,indent=2)+'\n');(out/'source-method-xml-bindings.json').write_text(json.dumps(refs,indent=2)+'\n');(out/'source-identities.json').write_text(json.dumps(sorted(sourceBindings.values(),key=lambda x:x['path']),indent=2)+'\n');(out/'independent-frozen-xml-check.json').write_text(json.dumps(checks,indent=2)+'\n');assert base.read_bytes()==original
print(json.dumps(checks,indent=2));print('DRAFTSHA',sha((out/'source87-individual-measured-review.json').read_bytes()))
